using Linq.Cmd._4_OutputFromQueries;
using Linq.Cmd._3_FilteringAndOrdering;
using Linq.Cmd._4_OutputFromQueries;
using Linq.Cmd._4_OutputFromQueries;
using Linq.Cmd._4_OutputFromQueries;
using Linq.Cmd._5_PartialResults;
using Linq.Cmd._5_PartialResults;
using Linq.Cmd._6_CheckingContents;

//new DeferredExecution().Run();
//new GetSingleItem().Run();
//new ProjectingResults().Run();
//new ChunkedResult().Run();
//new SkipAndTake().Run();
//new GroupedResults().Run();
//new RemoveDuplicates().Run();
//new CheckingForSingleItem().Run();
//new FindMatches().Run();
new AggregateFunctions().Run();